# Generated by Django 5.1.6 on 2025-02-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255)),
                ('zanr', models.CharField(max_length=100)),
                ('rok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255)),
                ('platforma', models.CharField(max_length=100)),
                ('rok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=100)),
                ('rok', models.IntegerField()),
            ],
        ),
    ]
