# Generated by Django 5.1.6 on 2025-02-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hra',
            name='zanr',
            field=models.CharField(default='Neurčeno', max_length=100),
        ),
        migrations.AddField(
            model_name='kniha',
            name='zanr',
            field=models.CharField(default='Neurčeno', max_length=100),
        ),
    ]
